"""Init POIs

Revision ID: 5cef38496ec5
Revises: 
Create Date: 2026-08-19 18:22:57.081184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cef38496ec5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attractions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('financials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scoring', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_city_category', 'attractions', ['city', 'category'], unique=False)
    op.create_index(op.f('ix_attractions_city'), 'attractions', ['city'], unique=False)
    op.create_index(op.f('ix_attractions_id'), 'attractions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attractions_id'), table_name='attractions')
    op.drop_index(op.f('ix_attractions_city'), table_name='attractions')
    op.drop_index('idx_city_category', table_name='attractions')
    op.drop_table('attractions')
    # ### end Alembic commands ###
